### ISSUE TITLE
想问问上海核酸码（非健康码）的url怎么抓取

### ISSUE THREAD

**Issue by xlangzhong** [JdaieLin/health-code-url-scheme#3]

**Comment by MeizuM9** [comment]
您好，来信已收到！

**Comment by JdaieLin** [comment]
目前只有支付宝小程序可以抓取，使用安卓手机进入到支付宝小程序页面，复制url，后部分有scheme可以使用

**Comment by JdaieLin** [comment]
试试看是不是这个
https://render.alipay.com/p/s/i/?scheme=alipays%3A%2F%2Fplatformapi%2Fstartapp%3FappId%3D2019072665939857%26page%3DpackageB%252Fpages%252Fantigen-check%252Fantigen-check%26enbsv%3D0.2.2204212106.3%26chInfo%3Dch_share__chsub_CopyLink%26apshareid%3D3536D832-C348-45D1-B974-7FB68F5F7258

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xlangzhong ***@***.***&gt;
发送时间: 2022年4月21日 11:05
收件人: JdaieLin/health-code-url-scheme ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [JdaieLin/health-code-url-scheme] 想问问上海核酸码（非健康码）的url怎么抓取 (Issue #3)

**Comment by JdaieLin** [comment]
@xlangzhong 试了一下应该不行，核酸码页面分享出来的链接无法进到那个页面，小程序内部可能做了一些处理

**Comment by xlangzhong** [comment]
@JdaieLin 好的

**Comment by MeizuM9** [comment]
您好，来信已收到！

**Comment by pallxk** [comment]
```
alipays://platformapi/startapp?appId=2019072665939857&page=packageB/pages/newMWPage/newMWPage?key=HS
```
